import {
  Listing,
  TrustPoint,
  CategoryInfo,
  Stat,
  TeamMember,
  BusinessInfo,
} from '@/types';

// TODO: Connect to backend API — GET /api/listings
export const listings: Listing[] = [
  {
    id: '1',
    slug: 'toyota-land-cruiser-300-2024',
    name: 'Toyota Land Cruiser 300',
    category: 'Cars',
    brand: 'Toyota',
    model: 'Land Cruiser 300',
    year: 2024,
    price: 85000000,
    mileage: 12000,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    driveSystem: '4WD',
    condition: 'Used',
    color: 'Pearl White',
    description:
      'The legendary Toyota Land Cruiser 300 series represents the pinnacle of off-road luxury. This immaculate example features the twin-turbo V6 engine, delivering exceptional power while maintaining impressive fuel efficiency. Perfect for Nigerian roads and perfect for those who demand the best.',
    specifications: {
      Make: 'Toyota',
      Model: 'Land Cruiser 300',
      Year: '2024',
      Engine: '3.3L Twin-Turbo V6 Diesel',
      Horsepower: '309 HP',
      Transmission: '10-Speed Automatic',
      'Drive Type': '4WD',
      'Fuel Type': 'Diesel',
      Mileage: '12,000 km',
      Seating: '7',
      'Body Type': 'SUV',
      Colour: 'Pearl White',
    },
    features: [
      'Leather Interior',
      'Sunroof',
      '360° Camera',
      'Adaptive Cruise Control',
      'Apple CarPlay',
      'Android Auto',
      'Heated Seats',
      'Cooled Seats',
    ],
    images: [
      'https://images.pexels.com/photos/1204072/pexels-photo-1204072.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1708118/pexels-photo-1708118.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: true,
    published: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    slug: 'john-deere-6r-2023',
    name: 'John Deere 6R Series Tractor',
    category: 'Tractors',
    brand: 'John Deere',
    model: '6R 185',
    year: 2023,
    price: 120000000,
    hoursUsed: 850,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    driveSystem: '4WD',
    condition: 'Used',
    color: 'John Deere Green',
    description:
      'A versatile and powerful tractor ideal for medium to large farming operations. This John Deere 6R 185 features the PowrQuad transmission and is equipped with front loader compatibility. Excellent condition with comprehensive service history. Perfect for Nigerian agricultural needs.',
    specifications: {
      Make: 'John Deere',
      Model: '6R 185',
      Year: '2023',
      'Engine Power': '185 HP',
      'Operating Hours': '850',
      'Fuel Type': 'Diesel',
      'Drive System': '4WD',
      'Lift Capacity': '5,400 kg',
      'Dimensions': '4.3m x 2.4m x 2.8m',
      Weight: '6,200 kg',
      Colour: 'John Deere Green',
    },
    features: [
      'GPS Ready',
      'Front Loader Compatible',
      'Climate Controlled Cab',
      'Power Beyond Hydraulics',
      'Air Suspension Seat',
    ],
    images: [
      'https://images.pexels.com/photos/598060/pexels-photo-598060.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/2165759/pexels-photo-2165759.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: true,
    published: true,
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    slug: 'caterpillar-320-excavator-2022',
    name: 'Caterpillar 320 Excavator',
    category: 'Excavators',
    brand: 'Caterpillar',
    model: '320 GC',
    year: 2022,
    price: 180000000,
    hoursUsed: 2100,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    driveSystem: 'N/A',
    condition: 'Used',
    color: 'Caterpillar Yellow',
    description:
      'This Caterpillar 320 GC excavator is built for reliability and low operating costs. Perfect for general construction, utilities, and quarry applications. The machine shows moderate use at 2,100 hours and has been maintained to Caterpillar specifications.',
    specifications: {
      Make: 'Caterpillar',
      Model: '320 GC',
      Year: '2022',
      'Engine Power': '162 HP',
      'Operating Hours': '2,100',
      'Fuel Type': 'Diesel',
      'Operating Weight': '20,300 kg',
      'Bucket Capacity': '1.0 m³',
      'Max Dig Depth': '6.7m',
      Colour: 'Caterpillar Yellow',
    },
    features: [
      'Quick Coupler',
      'Hydraulic Thumb',
      'Grade Control Ready',
      'Rear Camera',
      'Climate Control Cab',
    ],
    images: [
      'https://images.pexels.com/photos/1212682/pexels-photo-1212682.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/2760241/pexels-photo-2760241.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: true,
    published: true,
    createdAt: '2024-01-05',
  },
  {
    id: '4',
    slug: 'mercedes-gls-450-2024',
    name: 'Mercedes-Benz GLS 450',
    category: 'Cars',
    brand: 'Mercedes-Benz',
    model: 'GLS 450',
    year: 2024,
    price: 95000000,
    mileage: 5000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    driveSystem: 'AWD',
    condition: 'Used',
    color: 'Obsidian Black',
    description:
      'The Mercedes-Benz GLS 450 4MATIC+ is the S-Class of SUVs. This stunning example combines breathtaking performance with unmatched comfort. With only 5,000 km, this vehicle is essentially new with significant savings off the new car price.',
    specifications: {
      Make: 'Mercedes-Benz',
      Model: 'GLS 450',
      Year: '2024',
      Engine: '3.0L Turbo Inline-6 + EQ Boost',
      Horsepower: '362 HP',
      Transmission: '9-Speed Automatic',
      'Drive Type': 'AWD',
      'Fuel Type': 'Petrol',
      Mileage: '5,000 km',
      Seating: '7',
      'Body Type': 'SUV',
      Colour: 'Obsidian Black',
    },
    features: [
      'Executive Rear Seats',
      'MBUX Infotainment',
      'Burmester Sound',
      'AIRMATIC Suspension',
      'Night Package',
      'Panoramic Roof',
    ],
    images: [
      'https://images.pexels.com/photos/1204072/pexels-photo-1204072.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/707046/pexels-photo-707046.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: true,
    published: true,
    createdAt: '2024-01-12',
  },
  {
    id: '5',
    slug: 'ford-f-150-raptor-2023',
    name: 'Ford F-150 Raptor',
    category: 'Trucks',
    brand: 'Ford',
    model: 'F-150 Raptor',
    year: 2023,
    price: 65000000,
    mileage: 28000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    driveSystem: '4WD',
    condition: 'Used',
    color: 'Velocity Blue',
    description:
      'The ultimate desert-running powerhouse. This Ford F-150 Raptor is equipped with the high-output 3.5L EcoBoost V6 and Fox Live Valve shocks. Built for off-road enthusiasts who demand the best.',
    specifications: {
      Make: 'Ford',
      Model: 'F-150 Raptor',
      Year: '2023',
      Engine: '3.5L High-Output EcoBoost V6',
      Horsepower: '450 HP',
      Transmission: '10-Speed Automatic',
      'Drive Type': '4WD',
      'Fuel Type': 'Petrol',
      Mileage: '28,000 km',
      Seating: '5',
      'Body Type': 'Pickup Truck',
      Colour: 'Velocity Blue',
    },
    features: [
      'FOX Live Valve Shocks',
      'Terrain Management System',
      'Pro Power Onboard',
      'B&O Sound System',
      'Recaro Seats',
    ],
    images: [
      'https://images.pexels.com/photos/4601820/pexels-photo-4601820.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/11667880/pexels-photo-11667880.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: false,
    published: true,
    createdAt: '2024-01-08',
  },
  {
    id: '6',
    slug: 'kubota-m7-tractor-2022',
    name: 'Kubota M7-172 Tractor',
    category: 'Tractors',
    brand: 'Kubota',
    model: 'M7-172',
    year: 2022,
    price: 75000000,
    hoursUsed: 1500,
    transmission: 'Manual',
    fuelType: 'Diesel',
    driveSystem: '4WD',
    condition: 'Used',
    color: 'Kubota Orange',
    description:
      'A reliable and efficient medium-range tractor perfect for livestock and cropping operations. This Kubota M7 features a spacious cab with excellent visibility and low operating hours.',
    specifications: {
      Make: 'Kubota',
      Model: 'M7-172',
      Year: '2022',
      'Engine Power': '170 HP',
      'Operating Hours': '1,500',
      'Fuel Type': 'Diesel',
      'Drive System': '4WD',
      'Lift Capacity': '4,800 kg',
      Weight: '5,800 kg',
      Colour: 'Kubota Orange',
    },
    features: [
      'Front Linkage',
      'Air Conditioned Cab',
      'GPS Guidance Ready',
      'Dual Hydraulic Remotes',
    ],
    images: [
      'https://images.pexels.com/photos/598060/pexels-photo-598060.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: false,
    published: true,
    createdAt: '2024-01-03',
  },
  {
    id: '7',
    slug: 'hitachi-zx220-excavator-2021',
    name: 'Hitachi ZX220LC-6',
    category: 'Excavators',
    brand: 'Hitachi',
    model: 'ZX220LC-6',
    year: 2021,
    price: 140000000,
    hoursUsed: 3800,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    driveSystem: 'N/A',
    condition: 'Used',
    color: 'Hitachi Orange',
    description:
      'A robust mid-sized excavator ideal for construction and earthmoving applications. This ZX220LC-6 comes with excellent service history.',
    specifications: {
      Make: 'Hitachi',
      Model: 'ZX220LC-6',
      Year: '2021',
      'Engine Power': '162 HP',
      'Operating Hours': '3,800',
      'Fuel Type': 'Diesel',
      'Operating Weight': '22,000 kg',
      'Max Dig Depth': '6.4m',
      Colour: 'Hitachi Orange',
    },
    features: [
      'Quick Hitch',
      'Tilting Bucket',
      'Ripper Tooth',
      'Safety Camera',
    ],
    images: [
      'https://images.pexels.com/photos/2760241/pexels-photo-2760241.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: false,
    published: true,
    createdAt: '2023-12-28',
  },
  {
    id: '8',
    slug: 'volvo-a25g-articulated-hauler-2023',
    name: 'Volvo A25G Articulated Hauler',
    category: 'Heavy Machinery',
    brand: 'Volvo',
    model: 'A25G',
    year: 2023,
    price: 280000000,
    hoursUsed: 1200,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    driveSystem: '6x6',
    condition: 'Used',
    color: 'Volvo Yellow',
    description:
      'The Volvo A25G is a premium articulated hauler built for tough off-road conditions. Exceptional fuel efficiency and operator comfort.',
    specifications: {
      Make: 'Volvo',
      Model: 'A25G',
      Year: '2023',
      'Engine Power': '343 HP',
      'Operating Hours': '1,200',
      'Fuel Type': 'Diesel',
      'Payload Capacity': '25 tonnes',
      'Max Speed': '55 km/h',
      Weight: '23,500 kg',
      Colour: 'Volvo Yellow',
    },
    features: [
      'Suspension Seat',
      'Climate Control',
      'Load Weighing System',
      'Automatic Traction Control',
    ],
    images: [
      'https://images.pexels.com/photos/2760241/pexels-photo-2760241.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: false,
    published: true,
    createdAt: '2024-01-01',
  },
  {
    id: '9',
    slug: 'toyota-camry-2023',
    name: 'Toyota Camry 2023',
    category: 'Cars',
    brand: 'Toyota',
    model: 'Camry',
    year: 2023,
    price: 32000000,
    mileage: 15000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    driveSystem: 'FWD',
    condition: 'Used',
    color: 'Midnight Blue',
    description:
      'The Toyota Camry remains one of Nigeria\'s most reliable sedans. This clean example offers comfort, fuel efficiency, and the legendary Toyota reliability. Perfect for daily commuting or intercity travel.',
    specifications: {
      Make: 'Toyota',
      Model: 'Camry',
      Year: '2023',
      Engine: '2.5L 4-Cylinder',
      Horsepower: '206 HP',
      Transmission: '8-Speed Automatic',
      'Drive Type': 'FWD',
      'Fuel Type': 'Petrol',
      Mileage: '15,000 km',
      Seating: '5',
      'Body Type': 'Sedan',
      Colour: 'Midnight Blue',
    },
    features: [
      'Apple CarPlay',
      'Android Auto',
      'Push Start',
      'Reverse Camera',
      'Leather Seats',
      'Sunroof',
    ],
    images: [
      'https://images.pexels.com/photos/1592384/pexels-photo-1592384.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: false,
    published: true,
    createdAt: '2024-01-14',
  },
  {
    id: '10',
    slug: 'jcb-loadall-2022',
    name: 'JCB 540-140 Loadall',
    category: 'Equipment',
    brand: 'JCB',
    model: '540-140',
    year: 2022,
    price: 65000000,
    hoursUsed: 2200,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    driveSystem: '4WD',
    condition: 'Used',
    color: 'JCB Yellow',
    description:
      'Versatile telescopic handler perfect for agricultural and construction applications. High reach and impressive lift capacity.',
    specifications: {
      Make: 'JCB',
      Model: '540-140',
      Year: '2022',
      'Engine Power': '100 HP',
      'Operating Hours': '2,200',
      'Fuel Type': 'Diesel',
      'Max Lift Height': '14m',
      'Lift Capacity': '4,000 kg',
      Colour: 'JCB Yellow',
    },
    features: ['Quick Attach', 'Forks Included', 'Stabilizers', 'Cab Guard'],
    images: [
      'https://images.pexels.com/photos/2760241/pexels-photo-2760241.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: false,
    published: true,
    createdAt: '2023-12-20',
  },
];

// TODO: Connect to backend API — GET /api/listings/featured
export const featuredListings: Listing[] = listings.filter(
  (listing) => listing.featured
);

// TODO: Connect to backend API — GET /api/categories
export const categories: CategoryInfo[] = [
  {
    name: 'Cars',
    slug: 'cars',
    icon: 'Car',
    listingCount: listings.filter((l) => l.category === 'Cars').length,
  },
  {
    name: 'Trucks',
    slug: 'trucks',
    icon: 'Truck',
    listingCount: listings.filter((l) => l.category === 'Trucks').length,
  },
  {
    name: 'Tractors',
    slug: 'tractors',
    icon: 'Tractor',
    listingCount: listings.filter((l) => l.category === 'Tractors').length,
  },
  {
    name: 'Excavators',
    slug: 'excavators',
    icon: 'HardHat',
    listingCount: listings.filter((l) => l.category === 'Excavators').length,
  },
  {
    name: 'Heavy Machinery',
    slug: 'heavy-machinery',
    icon: 'Cog',
    listingCount: listings.filter((l) => l.category === 'Heavy Machinery').length,
  },
  {
    name: 'Equipment',
    slug: 'equipment',
    icon: 'Package',
    listingCount: listings.filter((l) => l.category === 'Equipment').length,
  },
];

// TODO: Connect to backend API — GET /api/trust-points
export const trustPoints: TrustPoint[] = [
  {
    id: '1',
    icon: 'ShieldCheck',
    title: 'Verified Listings',
    description:
      'Every vehicle and machine goes through a quality check before listing.',
  },
  {
    id: '2',
    icon: 'Eye',
    title: 'Transparent Pricing',
    description:
      'No hidden fees, no pressure. What you see is the price.',
  },
  {
    id: '3',
    icon: 'Globe',
    title: 'Wide Selection',
    description:
      'Cars, trucks, tractors, and heavy machinery — all in one place.',
  },
  {
    id: '4',
    icon: 'Phone',
    title: 'Direct Contact',
    description:
      'Talk to us directly — call, WhatsApp, or email. No middlemen.',
  },
];

// TODO: Connect to backend API — GET /api/stats
export const stats: Stat[] = [
  { label: 'Years in Business', value: 8, suffix: '+' },
  { label: 'Units Sold', value: 500, suffix: '+' },
  { label: 'Happy Clients', value: 350, suffix: '+' },
];

// TODO: Connect to backend API — GET /api/team
export const teamMembers: TeamMember[] = [
  {
    name: 'Adewale Okonkwo',
    role: 'Founder & Managing Director',
    image: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
    bio: 'With over 15 years in the automotive and machinery industry, Adewale founded DX STAR EMPORIUM with a vision for quality and trust.',
  },
  {
    name: 'Chioma Nwankwo',
    role: 'Head of Operations',
    image: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=400',
    bio: 'Chioma ensures every vehicle and piece of machinery meets our rigorous standards before reaching our showroom.',
  },
  {
    name: 'Emeka Obi',
    role: 'Lead Sales Consultant',
    image: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=400',
    bio: 'Emeka brings deep knowledge of both luxury vehicles and industrial equipment to help clients find the perfect fit.',
  },
];

// TODO: Connect to backend API — GET /api/business-info
export const businessInfo: BusinessInfo = {
  name: 'DX STAR EMPORIUM',
  tagline: 'Quality Vehicles and Equipment',
  phone: '+234 803 456 7890',
  whatsapp: '2348034567890',
  email: 'info@dx staremporium.com',
  address: '15 Adeniran Ogunsanya Street, Surulere, Lagos, Nigeria',
  hours: [
    { day: 'Monday', open: '9:00 AM', close: '6:00 PM', closed: false },
    { day: 'Tuesday', open: '9:00 AM', close: '6:00 PM', closed: false },
    { day: 'Wednesday', open: '9:00 AM', close: '6:00 PM', closed: false },
    { day: 'Thursday', open: '9:00 AM', close: '6:00 PM', closed: false },
    { day: 'Friday', open: '9:00 AM', close: '6:00 PM', closed: false },
    { day: 'Saturday', open: '10:00 AM', close: '4:00 PM', closed: false },
    { day: 'Sunday', open: 'N/A', close: 'N/A', closed: true },
  ],
  socialMedia: [
    { platform: 'Facebook', url: 'https://facebook.com/dx staremporium' },
    { platform: 'Instagram', url: 'https://instagram.com/dx staremporium' },
    { platform: 'LinkedIn', url: 'https://linkedin.com/company/dx staremporium' },
  ],
};

// TODO: Connect to backend API — GET /api/brands
export const brands = [
  'Toyota',
  'Ford',
  'Mercedes-Benz',
  'BMW',
  'Lexus',
  'Honda',
  'John Deere',
  'Caterpillar',
  'Kubota',
  'Hitachi',
  'Volvo',
  'JCB',
];

// TODO: Connect to backend API — GET /api/search-filters
export const filterOptions = {
  categories: categories.map((c) => c.name),
  conditions: ['New', 'Used'] as const,
  brands,
  fuelTypes: ['Petrol', 'Diesel', 'Electric', 'Hybrid', 'N/A'] as const,
  transmissions: ['Automatic', 'Manual', 'N/A'] as const,
  priceRange: {
    min: 10000000,
    max: 500000000,
  },
  yearRange: {
    min: 2015,
    max: 2024,
  },
};
